### ISSUE TITLE
Reloading

### ISSUE THREAD

**Issue by Oupsla** [Oupsla/Dashboard-Pr#1]
- Try to not losing selected repo when reloading page
- Reload or change the array of a new assigned pr or an unassigned pr
- Mdt-Table are not linked to model (related to https://github.com/iamisti/mdDataTable/issues/25)

**Comment by denishamann** [comment]
- Selected repo is not lost anymore
- Page reload after assignement or unassignement --> ok
- mdt-table --> still problems with double loading
